version: '3.1'
services:
  database:
    image: 'mysql:latest'
    restart: always
    environment:
      MYSQL_DATABASE: vivmonitors
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_USER: stats_collector
      MYSQL_PASSWORD: changeme
  collector:
    image: 'stats_collector:latest'
    restart: always
    ports:
      - '5000:5000'
    environment:
      DB_CONN: 'mysql+pymysql://stats_collector:changeme@database/vivmonitors'
      PORT: 5000
      FIRMWARE_URL: 'https://github.com/saljs/viv_clients/releases/latest/download/fw_bundle.zip'
  grafana:
    image: 'grafana/grafana:latest'
    restart: always
    ports:
      - '3000:80'
