version: '3.1'
services:
  database:
    image: 'hypriot/rpi-mysql:latest'
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: vivmonitors
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_USER: stats_collector
      MYSQL_PASSWORD: changeme
  collector:
    image: 'stats_collector:latest'
    restart: always
    ports:
      - '5000:5000'
    environment:
      DB_CONN: 'mysql+pymysql://stats_collector:changeme@database/vivmonitors'
      PORT: 5000
  backups:
    image: 'backup-server:latest'
    restart: always
    volumes:
      - '/mnt/backup:/backups'
    environment:
      DB_HOST: database
      DB_PORT: 3306
      DB_USER: stats_collector
      DB_PASSWORD: changeme
      OUT_PATH: '/backups'
